sudo: required
service:
 - docker

before_install:
 - docker build -t vishwakv/react-test -f ./client/Dockerfile.dev ./client

scripts:
 - docker run -e CI=true vishwakv/react-test npm test

after_success:
 - docker build -t vinvishwa007/multi-client ./client
 - docker build -t vinvishwa007/multi-nginx ./nginx
 - docker build -t vinvishwa007/multi-server ./server
 - docker build -t vinvishwa007/multi-worker ./worker
 #login to the docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take those images and push them to docker hub
 - docker push vinvishwa007/multi-client
 - docker push vinvishwa007/multi-nginx
 - docker push vinvishwa007/multi-server
 - docker push vinvishwa007/multi-worker
